[package]
name = "chiikawa"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "ğŸŒ¸ ã¡ã„ã‹ã‚ï¼ ğŸŒ¸"
readme = "README.md"
homepage = "https://github.com/ekusiadadus/chiikawa-cli"
repository = "https://github.com/ekusiadadus/chiikawa-cli"
keywords = ["cli", "Japan", "Rust"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
